<?php
// export-users.php - Export user data as CSV
session_start();
require_once 'config.php';

// Check if user is admin
if (!isset($_SESSION['user_id']) || $_SESSION['is_admin'] != 1) {
    header("Location: login.php");
    exit();
}

// Get filter from URL (optional)
$user_filter = isset($_GET['filter']) ? $_GET['filter'] : 'all';

// Build query based on filter
$where_clause = "";
if ($user_filter == 'admin') {
    $where_clause = "WHERE u.is_admin = 1";
} elseif ($user_filter == 'regular') {
    $where_clause = "WHERE u.is_admin = 0";
} elseif ($user_filter == 'nutritionist') {
    $where_clause = "WHERE u.user_type = 'Nutritionist'";
}

// Get all users with their stats
$users_query = "SELECT 
                u.user_id,
                u.full_name,
                u.email,
                u.user_type,
                u.phone_number,
                u.date_registered,
                u.is_admin,
                COUNT(DISTINCT mp.mealplan_id) as total_plans,
                COUNT(DISTINCT ua.activity_id) as total_activities,
                COALESCE(ub.amount, 0) as budget_amount,
                (SELECT COUNT(*) FROM pantry WHERE user_id = u.user_id) as pantry_items
                FROM users u
                LEFT JOIN meal_plans mp ON u.user_id = mp.user_id
                LEFT JOIN user_activity ua ON u.user_id = ua.user_id
                LEFT JOIN user_budgets ub ON u.user_id = ub.user_id AND ub.status = 'Active'
                $where_clause
                GROUP BY u.user_id
                ORDER BY u.date_registered DESC";

$result = mysqli_query($conn, $users_query);

if (!$result) {
    die("Query failed: " . mysqli_error($conn));
}

// Set filename with current date
$filename = "nutriplan_users_" . date('Y-m-d') . ".csv";

// Set headers for CSV download
header('Content-Type: text/csv; charset=utf-8');
header('Content-Disposition: attachment; filename="' . $filename . '"');

// Create output stream
$output = fopen('php://output', 'w');

// Add UTF-8 BOM for Excel compatibility
fprintf($output, chr(0xEF).chr(0xBB).chr(0xBF));

// Add CSV headers
fputcsv($output, [
    'User ID',
    'Full Name',
    'Email',
    'User Type',
    'Phone Number',
    'Registration Date',
    'Role',
    'Total Meal Plans',
    'Total Activities',
    'Pantry Items',
    'Active Budget (KES)',
    'Status'
]);

// Add data rows
while ($row = mysqli_fetch_assoc($result)) {
    // Determine status (active in last 7 days)
    $user_id = $row['user_id'];
    $active_check = mysqli_query($conn, "SELECT activity_id FROM user_activity WHERE user_id = $user_id AND created_at >= DATE_SUB(NOW(), INTERVAL 7 DAY) LIMIT 1");
    $status = (mysqli_num_rows($active_check) > 0) ? 'Active' : 'Inactive';
    
    // Format date
    $reg_date = date('Y-m-d', strtotime($row['date_registered']));
    
    // Determine role
    $role = ($row['is_admin'] == 1) ? 'Administrator' : 'Regular User';
    
    // Format data for CSV
    $data = [
        $row['user_id'],
        $row['full_name'],
        $row['email'],
        $row['user_type'],
        $row['phone_number'] ?: 'N/A',
        $reg_date,
        $role,
        $row['total_plans'] ?: 0,
        $row['total_activities'] ?: 0,
        $row['pantry_items'] ?: 0,
        $row['budget_amount'] ?: 0,
        $status
    ];
    
    fputcsv($output, $data);
}

// Add summary row
fputcsv($output, []); // Empty row
fputcsv($output, ['GENERATED BY', 'NutriPlan KE Admin Dashboard']);
fputcsv($output, ['EXPORT DATE', date('Y-m-d H:i:s')]);
fputcsv($output, ['TOTAL USERS', mysqli_num_rows($result)]);

// Close the output stream
fclose($output);
exit();
?>