<?php
// export-nutrition.php - Export nutritional data as CSV
session_start();
require_once 'config.php';

// Check if user is admin
if (!isset($_SESSION['user_id']) || $_SESSION['is_admin'] != 1) {
    header("Location: login.php");
    exit();
}

// Get all recipes with nutritional data
$recipes_query = "SELECT 
                  recipe_id,
                  recipe_name,
                  description,
                  meal_type,
                  prep_time,
                  serving_size,
                  estimated_cost,
                  calories,
                  protein,
                  carbs,
                  fats,
                  created_at
                  FROM recipes 
                  ORDER BY meal_type, recipe_name";

$result = mysqli_query($conn, $recipes_query);

if (!$result) {
    die("Query failed: " . mysqli_error($conn));
}

// Set filename
$filename = "nutriplan_nutrition_data_" . date('Y-m-d') . ".csv";

// Set headers for CSV download
header('Content-Type: text/csv; charset=utf-8');
header('Content-Disposition: attachment; filename="' . $filename . '"');

// Create output stream
$output = fopen('php://output', 'w');

// Add UTF-8 BOM for Excel compatibility
fprintf($output, chr(0xEF).chr(0xBB).chr(0xBF));

// Add CSV headers
fputcsv($output, [
    'Recipe ID',
    'Recipe Name',
    'Description',
    'Meal Type',
    'Prep Time',
    'Serving Size',
    'Estimated Cost (KES)',
    'Calories',
    'Protein (g)',
    'Carbs (g)',
    'Fats (g)',
    'Date Added'
]);

// Calculate totals
$total_recipes = 0;
$total_calories = 0;
$total_protein = 0;
$total_carbs = 0;
$total_fats = 0;
$total_cost = 0;

// Add data rows
while ($row = mysqli_fetch_assoc($result)) {
    $data = [
        $row['recipe_id'],
        $row['recipe_name'],
        $row['description'] ?: 'N/A',
        $row['meal_type'] ?: 'N/A',
        $row['prep_time'] ?: 'N/A',
        $row['serving_size'] ?: 'N/A',
        $row['estimated_cost'] ?: 0,
        $row['calories'] ?: 0,
        $row['protein'] ?: 0,
        $row['carbs'] ?: 0,
        $row['fats'] ?: 0,
        date('Y-m-d', strtotime($row['created_at']))
    ];
    
    fputcsv($output, $data);
    
    // Update totals
    $total_recipes++;
    $total_calories += $row['calories'] ?: 0;
    $total_protein += $row['protein'] ?: 0;
    $total_carbs += $row['carbs'] ?: 0;
    $total_fats += $row['fats'] ?: 0;
    $total_cost += $row['estimated_cost'] ?: 0;
}

// Calculate averages
$avg_calories = $total_recipes > 0 ? round($total_calories / $total_recipes, 1) : 0;
$avg_protein = $total_recipes > 0 ? round($total_protein / $total_recipes, 1) : 0;
$avg_carbs = $total_recipes > 0 ? round($total_carbs / $total_recipes, 1) : 0;
$avg_fats = $total_recipes > 0 ? round($total_fats / $total_recipes, 1) : 0;
$avg_cost = $total_recipes > 0 ? round($total_cost / $total_recipes, 1) : 0;

// Add summary section
fputcsv($output, []); // Empty row
fputcsv($output, ['SUMMARY STATISTICS']);
fputcsv($output, ['Total Recipes', $total_recipes]);
fputcsv($output, ['Average Calories', $avg_calories]);
fputcsv($output, ['Average Protein (g)', $avg_protein]);
fputcsv($output, ['Average Carbs (g)', $avg_carbs]);
fputcsv($output, ['Average Fats (g)', $avg_fats]);
fputcsv($output, ['Average Cost (KES)', $avg_cost]);
fputcsv($output, ['Total Calories', $total_calories]);
fputcsv($output, ['Total Protein (g)', $total_protein]);
fputcsv($output, ['Total Carbs (g)', $total_carbs]);
fputcsv($output, ['Total Fats (g)', $total_fats]);
fputcsv($output, ['Total Cost (KES)', $total_cost]);

fputcsv($output, []); // Empty row
fputcsv($output, ['GENERATED BY', 'NutriPlan KE Admin Dashboard']);
fputcsv($output, ['EXPORT DATE', date('Y-m-d H:i:s')]);

fclose($output);
exit();
?>